# Generated by Django 5.2.10 on 2026-01-19 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300, 'Description cannot exceed 300 characters.'), django.core.validators.MinLengthValidator(20, 'Description must be at least 20 characters long.')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Conference name must be at least 5 characters long.')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
