# Generated by Django 5.2.10 on 2026-02-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_alter_conference_description_alter_conference_name_and_more'),
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ConferenceApp.conference'),
            preserve_default=False,
        ),
    ]
